version: '3.6'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      # db name, db username, db password
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_PASSWORD=${MONGODB_PASSWORD}
    restart: always
    networks:
      - backend

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      #     사이트 접속 아이디
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  mongodb:
